function img = rendervol(imgpath, volpath)
% Renders a volume which has been generated by the VRN lua script.

vol = readvol(volpath, [192 192 200]);

im = imread(imgpath);
im = im(33:32+384, 33:32+384, :);
im = imresize(im, [192 192]);


Q = isosurface(vol);
Q.EdgeColor = 'none';
Q.FaceColor = [120 154 194]/255;

figure
imshow(im, 'Border', 'tight');
hold on
patch(Q);
hold on
h = camlight;
lightangle(h, -10, 80)
lighting gouraud
material dull
view(0,90)
cap = getframe;
img = cap.cdata;

